services:
  - type: web
    name: certificate-system
    env: docker
    plan: free
    region: ohio
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: PORT
        value: 8080
